export {
  CACHE_PRESETS,
  type CacheConfig,
  type CacheLine,
  type CachePreset,
  type CacheResult,
  type CacheSet,
  type CacheStep,
  decomposeAddress,
  generateTrace,
  naiveCache,
  reconstructAddress,
  runCache,
  type TraceKind,
} from "./cache.ts";

export {
  type ForwardInfo,
  type HazardMode,
  type Instruction,
  interpretSequential,
  makeAdd,
  makeAddi,
  makeAnd,
  makeBeq,
  makeLw,
  makeNop,
  makeOr,
  makeSub,
  makeSw,
  type OpCode,
  PIPELINE_PRESETS,
  type PipelinePreset,
  type PipelineResult,
  type PipelineStep,
  runPipeline,
  type StageName,
} from "./pipeline.ts";
